#! /bin/bash

set -e

PY_SRC_PATH=~/work/python
PY_DOC_PATH="$PY_SRC_PATH/Doc"

rm -Rf ,temp
rm -Rf html
mkdir ,temp
cd ,temp
for i in ../*.tex; do 
    python2.5 ../sub_verbatim.py $i > `basename $i`
done

export TEXINPUTS="$TEXINPUTS:$PY_DOC_PATH/texinputs" 
"$PY_DOC_PATH/tools/mkhowto" "$@"

latex "$@" || true
makeindex *.idx
latex "$@"
latex "$@"
DVINAME=`echo *.dvi`
dvips $DVINAME -o ${DVINAME%.dvi}.ps
ps2pdf *.ps
cp *.pdf ..
mv pylinear ../html
cd ..

rm -Rf ,temp
