#! /usr/bin/env python

import code
import pylinear
import sys

try:
    import readline
    HAVE_READLINE = True
except ImportError:
    HAVE_READLINE = False

class MyConsole(code.InteractiveConsole):
    def __init__(self):
        code.InteractiveConsole.__init__(self)
        if HAVE_READLINE:
            import os
            import atexit

            histfile = os.path.join(os.environ["HOME"], ".pylinearhist")
            if os.access(histfile, os.R_OK):
                readline.read_history_file(histfile)
            atexit.register(readline.write_history_file, histfile)
            readline.parse_and_bind("tab: complete")

cons = MyConsole()
cons.runsource("from pylinear.array import *")
cons.runsource("from pylinear.operator import *")
cons.runsource("from pylinear.computation import *")
cons.runsource("from pylinear.toybox import *")
cons.interact("PyLinear %s, running on Python %s\n"
% (".".join([str(i) for i in pylinear.version()]), sys.version))
